name: ci-build

on: [push]

jobs:
  build:

    strategy:
      matrix:
        docker_tag: 
        - archlinux
        - fedora-31
        - fedora-30
        - debian-stretch
        - debian-buster
        - ubuntu-18.04
        - ubuntu-19.10
        - opensuse-15.0
        - opensuse-15.1
        os: 
        - ubuntu-latest

    runs-on: ${{ matrix.os }}
    env:
      DOCKER_IMG: docker.pkg.github.com/jahnf/projecteur/projecteur
      DOCKER_TAG: ${{ docker_tag.env }}

    steps:
    - uses: actions/checkout@v1
    - name: Login to github docker registry
      run: docker login docker.pkg.github.com -u jahnf -p ${{ secrets.GITHUB_TOKEN }}
    - name: Pull ${{ matrix.env }} docker image
      run: docker pull ${DOCKER_IMG}:${{ docker_tag.env }}
    - name: docker create build container
      run: docker run --name build -d -v `pwd`:/source:ro -ti ${DOCKER_IMG}:${{ docker_img.env }}
    - name: cmake configuration
      run: docker exec -it build /bin/bash -c "mkdir -p /build/dist-pkg && cd /build && cmake /source"
    - name: cmake build
      run: docker exec -it build /bin/bash -c "cd /build && cmake --build ."  
